CREATE SEQUENCE SPECIALTY_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE SPECIALTY (
    ID      NUMBER(19)      NOT NULL,
    NAME    VARCHAR2(80 CHAR) NOT NULL,
    VERSION NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPECIALTY PRIMARY KEY (ID),
    CONSTRAINT UQ_SPECIALTY_NAME UNIQUE (NAME)
);